### ISSUE TITLE
I cannot get this to work.

### ISSUE THREAD

**Issue by Addamere** [easyfuckingpeasy/chrome-reddit-comment-highlights#11]
I am using Chrome, currently updated; Windows 10 64-bit; my other extensions are uBlock, which I've tried toggling on or off or even disabling; Reddit Enhancement Suite, which I've tried disabling; and HoverZoom, which I've also tried toggling; and, AutoReplay for YouTube.

Quite simply, I don't see new comments highlighted at all. Attached is a screenshot of a thread from /r/Pathfinder_RPG which clearly has an unread comment but none of the comments displayed are highlighted. You'll just have to take my word for it that I've tried this on multiple threads, and there exists the same problem.

I'm not using night mode or anything like that. What am I doing wrong? I installed to Chrome via the Chrome web store.

![image](https://user-images.githubusercontent.com/32933555/31775318-df41f3e0-b4ad-11e7-8dff-5f90709a4cde.png)

**Comment by aesy** [comment]
Hey,

You haven't done anything wrong as far as I can tell, but I need some more info to be able to figure out the issue. I assume you are using version `1.1.1` since you installed via the web store, correct?

Unfortunately I can't ask you to send me logs since there is no logging in place (I should do something about that...). Are you familiar with the developer console? Are you comfortable with me guiding you to check for errors and fetch the internal settings of the extension?

A small note though, the new comments indicator isn't necessarily synced up with the extension. I haven't looked into exactly when it resets but I know it may persist after browser refresh, while highlights does not.

**Comment by Addamere** [comment]
It has inexplicably started working all of a sudden, after about an hour of it consistently not. I changed nothing; in fact, I turned all my other extensions back on and it still works. I suspect PEBKAC, or gremlins. Right now it is working exactly as advertised, and I have no troubles. Thanks for the quick feedback regardless!

**Comment by aesy** [comment]
Haha well that's nice to hear, I'm closing the issue then!
